version: "3"
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
  webserver:
    image: kendisiz/my-express-app
    environment:
      - DB_PWD=yourStrong(!)Password
      - DB_PORT=1433
      - DB_HOST=database
    ports:
      - 3000:3000
              